### PR TITLE
Wait for node

### PR DESCRIPTION
**Pull request by raphink**

### CODE REVIEW

**Comment by mcanevet** [comment]
I get `id is a reserved field name for a resource` when trying to use this.

**Comment by mcanevet** [comment]
Looks like it's not enough. My acceptance tests shows that the resource is not idempotent...

**Comment by mcanevet** [comment]
@raphink I tried this patch again and it looks like it does now find the node it puppetdb. Do you have any idea why?

**Comment by raphink** [comment]
@mcanevet 	not sure what you mean or why you closed the PR?

**Comment by mcanevet** [comment]
@raphink I fixed the issue in https://github.com/camptocamp/terraform-provider-puppetdb/commit/b030dfc2c95e4602601a475208989d5c2f4bc941

**Pull request closed without merging**
